export const cameraURL = [
  "https://www.youtube.com/embed/4pZZIkEa7Lc",
  "https://www.youtube.com/embed/gCNeDWCI0vo",
  "https://www.youtube.com/embed/DW4Ck97qBP4",
  "https://www.youtube.com/embed/1_Ih0JYmkjI",
  "https://www.youtube.com/embed/5d90EU5X6Wg",
  "https://www.youtube.com/embed/lsU1kcqvxWk",
  "https://www.youtube.com/embed/PTnHhxRtet8",
  "https://www.youtube.com/embed/zoYsRCoHbQk",
  "https://www.youtube.com/embed/pN8Bo4CnAxI",
  "https://www.youtube.com/embed/4pZZIkEa7Lc",
  "https://www.youtube.com/embed/gCNeDWCI0vo",
  "https://www.youtube.com/embed/DW4Ck97qBP4",
  "https://www.youtube.com/embed/1_Ih0JYmkjI",
  "https://www.youtube.com/embed/5d90EU5X6Wg",
  "https://www.youtube.com/embed/lsU1kcqvxWk",
  "https://www.youtube.com/embed/PTnHhxRtet8",
  "https://www.youtube.com/embed/zoYsRCoHbQk",
  "https://www.youtube.com/embed/pN8Bo4CnAxI",
  "https://www.youtube.com/embed/DW4Ck97qBP4",
  "https://www.youtube.com/embed/1_Ih0JYmkjI",
  "https://www.youtube.com/embed/5d90EU5X6Wg",
  "https://www.youtube.com/embed/lsU1kcqvxWk",
  "https://www.youtube.com/embed/PTnHhxRtet8",
  "https://www.youtube.com/embed/zoYsRCoHbQk",
  "https://www.youtube.com/embed/pN8Bo4CnAxI",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
];